version: '3'

services:
  bot:
    build: .
    command: python main.py
    ports:
      - 443:443
    expose:
      - 3001
    volumes:
      - .:/code
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

