version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  bot:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 3001:3001
    depends_on:
      - redis
    restart: always
